AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM role for AI Wizard Terraform deployment with managed policies'

Parameters:
  TrustedAccount:
    Type: String
    Description: The AWS account ID that is allowed to assume this role

Resources:
  # Create the managed policy
  AIWizardManagedPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: AIWizardManagedPolicy
      Roles:
        - !Ref AIWizardDeploymentRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # S3 Global Permissions
          - Effect: Allow
            Action:
              - 's3:Describe*'
              - 's3:Get*'
              - 's3:List*'
              - 's3:TagResource'
            Resource: '*' 

          # S3 Permissions
          - Effect: Allow
            Action:
              - 's3:CreateBucket'
              - 's3:DeleteObject'
              - 's3:PutObject'
            Resource: 
              - "arn:aws:s3:::ai-wizard-terraform-state-*"
              - "arn:aws:s3:::ai-wizard-terraform-state-*/*"
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # CloudWatch Logs Global Permissions
          - Effect: Allow
            Action:
              - 'logs:Describe*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'logs:TagResource'
            Resource: '*'

          # CloudWatch Logs Permissions
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:FilterLogEvents'
              - 'logs:PutLogEvents'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # ECR Global Permissions
          - Effect: Allow
            Action:
              - 'ecr:Describe*'
              - 'ecr:Get*'
              - 'ecr:List*'
              - 'ecr:TagResource'
            Resource: '*'

          # ECR Permissions
          - Effect: Allow
            Action:
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:BatchGetImage'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:CreateRepository'
              - 'ecr:DeleteRepository'
              - 'ecr:DeleteRepositoryPolicy'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:SetRepositoryPolicy'
              - 'ecr:UntagResource'
              - 'ecr:UploadLayerPart'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # ECS Global Permissions
          - Effect: Allow
            Action:
              - 'ecs:Describe*'
              - 'ecs:Get*'
              - 'ecs:List*'
              - 'ecs:TagResource'
            Resource: '*'

          # ECS Permissions
          - Effect: Allow
            Action:
              - 'ecs:CreateCluster'
              - 'ecs:CreateService'
              - 'ecs:DeleteService'
              - 'ecs:RegisterTaskDefinition'
              - 'ecs:TagResource'
              - 'ecs:UntagResource'
              - 'ecs:UpdateService'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # RDS Global Permissions
          - Effect: Allow
            Action:
              - 'rds:Describe*'
              - 'rds:Get*'
              - 'rds:List*'
              - 'rds:TagResource'
            Resource: '*'

          # RDS Permissions
          - Effect: Allow
            Action:
              - 'rds:CreateDBInstance'
              - 'rds:CreateDBSubnetGroup'
              - 'rds:DeleteDBSubnetGroup'
              - 'rds:DeleteDBInstance'
              - 'rds:ModifyDBInstance'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # VPC Global Permissions
          - Effect: Allow
            Action:
              - 'ec2:CreateTags'
              - 'ec2:Describe*'
              - 'ec2:Get*'
              - 'ec2:List*'
              - 'ec2:TagResource'
            Resource: '*'

          # VPC Permissions
          - Effect: Allow
            Action:
              - 'ec2:AllocateAddress'
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:CreateSubnet'
              - 'ec2:CreateVpc'
              - 'ec2:DeleteTags'
              - 'ec2:RevokeSecurityGroupIngress'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"
               
          # Secrets Manager Global Permissions
          - Effect: Allow
            Action:
              - 'secretsmanager:Describe*'
              - 'secretsmanager:Get*'
              - 'secretsmanager:List*'
              - 'secretsmanager:TagResource'
            Resource: '*'

          # Secrets Manager Permissions
          - Effect: Allow
            Action:
              - 'secretsmanager:CreateSecret'
              - 'secretsmanager:DeleteSecret'
              - 'secretsmanager:PutSecretValue'
              - 'secretsmanager:UpdateSecret'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # SSM Global Permissions
          - Effect: Allow
            Action:
              - 'ssm:Describe*'
              - 'ssm:Get*'
              - 'ssm:List*'
              - 'ssm:TagResource'
            Resource: '*'

          # SSM Permissions
          - Effect: Allow
            Action:
              - 'ssm:DeleteParameter'
              - 'ssm:PutParameter'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # STS Global Permissions
          - Effect: Allow
            Action: 
              - 'sts:GetCallerIdentity'
              - 'sts:GetSessionToken'
              - 'sts:TagSession'
            Resource: '*'

          # STS Permissions
          - Effect: Allow
            Action: 
              - 'sts:AssumeRole'
            Resource: !Sub 'arn:aws:iam::${TrustedAccount}:role/AIWizardDeploymentRole'


          # IAM Global Permissions
          - Effect: Allow
            Action: 'iam:PassRole'
            Resource: '*'

          # IAM Permissions
          - Effect: Allow
            Action: 'iam:CreateRole'
            Resource: !Sub 'arn:aws:iam::${TrustedAccount}:role/ai-wizard-ecs-task-execution-role'

          # AWS Certificate Manager Global Permissions
          - Effect: Allow
            Action:
              - 'acm:Describe*'
              - 'acm:Get*'
              - 'acm:List*'
              - 'acm:TagResource'
            Resource: '*'

          # AWS Certificate Manager Permissions
          - Effect: Allow
            Action:
              - 'acm:AddTagsToCertificate'
              - 'acm:DeleteCertificate'
              - 'acm:RequestCertificate'
              - 'acm:RemoveTagsFromCertificate'
              - 'acm:UpdateCertificateOptions'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

          # Route53 Global Permissions
          - Effect: Allow
            Action:
              - 'route53:Describe*'
              - 'route53:Get*'
              - 'route53:List*'
              - 'route53:TagResource'
            Resource: '*'

          # Route53 Permissions
          - Effect: Allow
            Action:
              - 'route53:ChangeResourceRecordSets'
              - 'route53:ChangeTagsForResource'
            Resource: '*'
            Condition:
              StringEquals:
                "aws:ResourceTag/Project": "ai-wizard"

  # Create the IAM role
  AIWizardDeploymentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AIWizardDeploymentRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${TrustedAccount}:root'
                - !Sub 'arn:aws:iam::${TrustedAccount}:user/aws-deploy'
            Action: 
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      Policies: []  # No inline policies, managed policy will be attached

Outputs:
  RoleARN:
    Description: The ARN of the created IAM role
    Value: !GetAtt AIWizardDeploymentRole.Arn
    Export:
      Name: AIWizardDeploymentRoleARN
