AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM role for AI Wizard Terraform deployment with managed policies'

Parameters:
  TrustedAccount:
    Type: String
    Description: The AWS account ID that is allowed to assume this role
  Route53ZoneId:
    Type: String
    Description: The Route53 Hosted Zone ID for the domain
  S3BucketRegion:
    Type: String
    Description: The region of the S3 bucket

Resources:
  # Create the new managed policy for serverless resources
  AIWizardServerlessManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: AIWizardServerlessManagedPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:CreateBucket'
              - 's3:DeleteBucket'
              - 's3:PutObject'
              - 's3:Describe*'
              - 's3:Get*'
              - 's3:List*'
              - 's3:DeleteObject'
              - 's3:DeleteBucketPolicy'
              - 's3:DeleteBucketWebsite'
              - 's3:PutBucketPolicy'
              - 's3:PutBucketTagging'
              - 's3:PutBucketWebsite'
              - 's3:PutBucketPublicAccessBlock'
              - 's3:HeadBucket'
            Resource: 
              - !Sub 'arn:aws:s3:::ai-wizard-frontend-${TrustedAccount}-${S3BucketRegion}'
              - !Sub 'arn:aws:s3:::ai-wizard-frontend-${TrustedAccount}-${S3BucketRegion}/*'
              - !Sub 'arn:aws:s3:::ai-wizard-frontend-${TrustedAccount}-${S3BucketRegion}-*'
              - !Sub 'arn:aws:s3:::ai-wizard-frontend-${TrustedAccount}-${S3BucketRegion}-*/*'

          - Effect: Allow
            Action:
              - 'dynamodb:CreateTable'
              - 'dynamodb:DeleteTable'
              - 'dynamodb:Describe*'
              - 'dynamodb:Get*'
              - 'dynamodb:List*'
              - 'dynamodb:PutItem'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'dynamodb:TagResource'
              - 'dynamodb:UntagResource'
            Resource: 
              - !Sub 'arn:aws:dynamodb:${S3BucketRegion}:${TrustedAccount}:table/ai-wizard-table'
              - !Sub 'arn:aws:dynamodb:${S3BucketRegion}:${TrustedAccount}:table/ai-wizard-backend-table-*'

          - Effect: Allow
            Action:
              - 'lambda:CreateFunction'
              - 'lambda:DeleteFunction'
              - 'lambda:Describe*'
              - 'lambda:Get*'
              - 'lambda:List*'
              - 'lambda:InvokeFunction'
              - 'lambda:UpdateFunctionCode'
              - 'lambda:UpdateFunctionConfiguration'
              - 'lambda:TagResource'
              - 'lambda:UntagResource'
              - 'lambda:AddPermission'
              - 'lambda:RemovePermission'
              - 'lambda:DeleteFunctionConcurrency'
              - 'lambda:PutFunctionConcurrency'
              - 'lambda:CreateAlias'
              - 'lambda:DeleteAlias'
              - 'lambda:UpdateAlias'
              - 'lambda:PublishVersion'
            Resource: 
              - !Sub 'arn:aws:lambda:${S3BucketRegion}:${TrustedAccount}:function:ai-wizard-backend-*'

          - Effect: Allow
            Action:
              - 'cloudfront:CreateDistribution'
              - 'cloudfront:CreateCloudFrontOriginAccessIdentity'
              - 'cloudfront:DeleteCloudFrontOriginAccessIdentity'
              - 'cloudfront:UpdateCloudFrontOriginAccessIdentity'
              - 'cloudfront:Describe*'
              - 'cloudfront:Get*'
              - 'cloudfront:List*'
              - 'cloudfront:UpdateDistribution'
              - 'cloudfront:DeleteDistribution'
              - 'cloudfront:TagResource'
              - 'cloudfront:UntagResource'
              - 'cloudfront:CreateInvalidation'
            Resource: '*'

          - Effect: Allow
            Action:
              - 'route53:ChangeResourceRecordSets'
            Resource: !Sub 'arn:aws:route53:::hostedzone/${Route53ZoneId}'

          - Effect: Allow
            Action:
              - 'route53:Describe*'
              - 'route53:Get*'
              - 'route53:List*'
            Resource: '*'

          - Effect: Allow
            Action:
              - 'acm:RequestCertificate'
              - 'acm:Describe*'
              - 'acm:Get*'
              - 'acm:List*'
              - 'acm:DeleteCertificate'
              - 'acm:AddTagsToCertificate'
              - 'acm:RemoveTagsFromCertificate'
            Resource: '*'

          - Effect: Allow
            Action:
              - 'apigateway:Create*'
              - 'apigateway:Delete*'
              - 'apigateway:Get*'
              - 'apigateway:Put*'
              - 'apigateway:Test*'
              - 'apigateway:Update*'
              - 'apigateway:TagResource'
              - 'apigateway:UntagResource'
              - 'apigateway:PUT'
              - 'apigateway:POST'
              - 'apigateway:GET'
              - 'apigateway:DELETE'
              - 'apigateway:PATCH'
              - 'apigateway:OPTIONS'
              - 'apigateway:HEAD'
            Resource: 
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/restapis'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/restapis/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/apis'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/apis/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/stages'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/stages/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/tags'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/tags/*'

          - Effect: Allow
            Action:
              - 'iam:CreateRole'
              - 'iam:DeleteRole'
              - 'iam:AttachRolePolicy'
              - 'iam:DetachRolePolicy'
              - 'iam:Describe*'
              - 'iam:Get*'
              - 'iam:List*'
              - 'iam:PassRole'
              - 'iam:TagRole'
              - 'iam:UntagRole'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
            Resource: 
              - !Sub 'arn:aws:iam::${TrustedAccount}:role/ai-wizard-lambda-exec-role'
              - !Sub 'arn:aws:iam::${TrustedAccount}:role/ai-wizard-lambda-exec-role-*'
              - !Sub 'arn:aws:iam::${TrustedAccount}:role/api-gateway-cloudwatch-*'

          - Effect: Allow
            Action: 
              - 'sts:AssumeRole'
              - 'sts:TagSession'
            Resource: !Sub 'arn:aws:iam::${TrustedAccount}:role/AIWizardDeploymentRole'

          - Effect: Allow
            Action:
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:ListStacks'
              - 'cloudformation:DescribeStackResource'
              - 'cloudformation:DescribeStackResources'
              - 'cloudformation:DescribeStackEvents'
              - 'cloudformation:ValidateTemplate'
            Resource: 
              - !Sub 'arn:aws:cloudformation:${S3BucketRegion}:${TrustedAccount}:stack/*'

          - Effect: Allow
            Action:
              - 'apigateway:GET'
              - 'apigateway:POST'
              - 'apigateway:PUT'
              - 'apigateway:DELETE'
              - 'apigateway:PATCH'
              - 'apigateway:HEAD'
              - 'apigateway:OPTIONS'
              - 'apigateway:Get*'
              - 'apigateway:CreateDomainName'
              - 'apigateway:DeleteDomainName'
              - 'apigateway:UpdateDomainName'
              - 'apigateway:CreateBasePathMapping'
              - 'apigateway:DeleteBasePathMapping'
              - 'apigateway:UpdateBasePathMapping'
              - 'apigateway:UpdateMethodSettings'
            Resource: 
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/domainnames'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/domainnames/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/restapis'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/restapis/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/apikeys'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/apikeys/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/usageplans'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/usageplans/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/apis'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/apis/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/stages'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/stages/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/tags'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/tags/*'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/account'
              - !Sub 'arn:aws:apigateway:${S3BucketRegion}::/account/*'

          - Effect: Allow
            Action:
              - 'events:DeleteRule'
              - 'events:DescribeRule'
              - 'events:ListRuleNamesByTarget'
              - 'events:ListRules'
              - 'events:ListTargetsByRule'
              - 'events:PutRule'
              - 'events:PutTargets'
              - 'events:RemoveTargets'
            Resource: 
              - !Sub 'arn:aws:events:${S3BucketRegion}:${TrustedAccount}:rule/*'

          - Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
            Resource: 'arn:aws:iam::*:role/aws-service-role/ops.apigateway.amazonaws.com/AWSServiceRoleForAPIGateway'
                                      
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:GetLogEvents
              - logs:FilterLogEvents
              - logs:TagLogGroup
              - logs:UntagLogGroup
            Resource: 
              - 'arn:aws:logs:*:*:*'
  # Create the IAM role
  AIWizardDeploymentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AIWizardDeploymentRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${TrustedAccount}:root'
                - !Sub 'arn:aws:iam::${TrustedAccount}:user/aws-deploy'
            Action: 
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      ManagedPolicyArns:
        - !Ref AIWizardServerlessManagedPolicy

Outputs:
  RoleARN:
    Description: The ARN of the created IAM role
    Value: !GetAtt AIWizardDeploymentRole.Arn
    Export:
      Name: AIWizardDeploymentRoleARN
