name: Deploy Backend

on:
  workflow_run:
    workflows: ["Build & Push Backend Image"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'backend/terraform/**'
      - '.github/workflows/ci-cd-deploy-backend.yml'

env:
  ECR_REPOSITORY: ai-wizard
  TF_STATE_BUCKET: ai-wizard-terraform-state-${{ vars.TF_VAR_aws_region }}
  WORKING_DIRECTORY: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'push' && (
        contains(github.event.head_commit.modified, 'backend/terraform/') || 
        contains(github.event.head_commit.modified, '.github/workflows/ci-cd-deploy-backend.yml') ||
        github.ref == 'refs/heads/main'
      ))
    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      id: configure_aws_credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.TF_VAR_aws_region }}
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/AIWizardDeploymentRole
        mask-aws-account-id: 'false'
          
    - name: Get Caller Identity
      id: get_caller_identity
      run: aws sts get-caller-identity

    - name: Get current image tag from ECR
      id: get_current_image_tag
      run: |
        LATEST_TAG=$(aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Create S3 bucket for Terraform state
      id: create_s3_bucket
      run: |
        if ! aws s3 ls "s3://${TF_STATE_BUCKET}" 2>&1 | grep -q 'NoSuchBucket'; then
          echo "Terraform state bucket already exists"
        else
          echo "Creating Terraform state bucket"
          aws s3api create-bucket \
            --bucket ${TF_STATE_BUCKET} \
            --region ${{ vars.TF_VAR_aws_region }} \
            --create-bucket-configuration LocationConstraint=${{ vars.TF_VAR_aws_region }}
          
          # Enable versioning
          aws s3api put-bucket-versioning \
            --bucket ${TF_STATE_BUCKET} \
            --versioning-configuration Status=Enabled

          # Enable server-side encryption
          aws s3api put-bucket-encryption \
            --bucket ${TF_STATE_BUCKET} \
            --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

          # Block public access
          aws s3api put-public-access-block \
            --bucket ${TF_STATE_BUCKET} \
            --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
        
          # Set bucket policy
          aws s3api put-bucket-policy --bucket ${TF_STATE_BUCKET} --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:sts::${{ vars.TF_VAR_aws_account_id }}:assumed-role/AIWizardDeploymentRole/GitHubActions"
                },
                "Action": [
                  "s3:PutObject",
                  "s3:GetObject",
                  "s3:DeleteObject",
                  "s3:ListBucket"
                ],
                "Resource": [
                  "arn:aws:s3:::ai-wizard-terraform-state-${{ vars.TF_VAR_aws_region }}",
                  "arn:aws:s3:::ai-wizard-terraform-state-${{ vars.TF_VAR_aws_region }}/*"
                ]
              }
            ]
          }'
        fi
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Setup Terraform
      id: setup_terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      id: terraform_init
      run: |
        terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ vars.TF_VAR_aws_region }}" \
          -reconfigure
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Check if ECR Repository is managed by Terraform
      id: check_ecr_managed
      run: |
        if terraform state list | grep -q 'aws_ecr_repository.ai_wizard'; then
          echo "ECR repository is already managed by Terraform"
          echo "is_managed=true" >> $GITHUB_OUTPUT
        else
          echo "ECR repository is not managed by Terraform"
          echo "is_managed=false" >> $GITHUB_OUTPUT
        fi
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Import ECR Repository
      id: terraform_import_ecr_repository
      if: steps.check_ecr_managed.outputs.is_managed == 'false'
      run: |
        terraform import \
          -var="aws_account_id=${{ vars.TF_VAR_AWS_ACCOUNT_ID }}" \
          -var="aws_region=${{ vars.TF_VAR_AWS_REGION }}" \
          -var="postgres_db_username=${{ secrets.POSTGRES_DB_USERNAME }}" \
          -var="postgres_db_password=${{ secrets.POSTGRES_DB_PASSWORD }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="route53_zone_id=${{ secrets.ROUTE53_HOSTED_ZONE_ID }}" \
          -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
          -var="ecr_image_tag=${LATEST_TAG}" \
          -var="environment=production" \
          aws_ecr_repository.ai_wizard ${{ env.ECR_REPOSITORY }}
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Plan (Targeted)
      id: terraform_plan_targeted
      run: |
        terraform plan \
          -var="aws_account_id=${{ vars.TF_VAR_AWS_ACCOUNT_ID }}" \
          -var="aws_region=${{ vars.TF_VAR_AWS_REGION }}" \
          -var="postgres_db_username=${{ secrets.POSTGRES_DB_USERNAME }}" \
          -var="postgres_db_password=${{ secrets.POSTGRES_DB_PASSWORD }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="route53_zone_id=${{ secrets.ROUTE53_HOSTED_ZONE_ID }}" \
          -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
          -var="ecr_image_tag=${LATEST_TAG}" \
          -var="environment=production" \
          -target=aws_acm_certificate.ai_wizard \
          -out=tfplan_targeted
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Apply (Targeted)
      id: terraform_apply_targeted
      run: terraform apply -auto-approve tfplan_targeted
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Plan (Validation)
      id: terraform_plan_validation
      run: |
        terraform plan \
          -var="aws_account_id=${{ vars.TF_VAR_AWS_ACCOUNT_ID }}" \
          -var="aws_region=${{ vars.TF_VAR_AWS_REGION }}" \
          -var="postgres_db_username=${{ secrets.POSTGRES_DB_USERNAME }}" \
          -var="postgres_db_password=${{ secrets.POSTGRES_DB_PASSWORD }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="route53_zone_id=${{ secrets.ROUTE53_HOSTED_ZONE_ID }}" \
          -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
          -var="ecr_image_tag=${LATEST_TAG}" \
          -var="environment=production" \
          -target=aws_route53_record.acm_validation \
          -target=aws_acm_certificate_validation.ai_wizard \
          -out=tfplan_validation
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Apply (Validation)
      id: terraform_apply_validation
      run: terraform apply -auto-approve tfplan_validation
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Plan (Full)
      id: terraform_plan
      run: |
        terraform plan \
          -var="aws_account_id=${{ vars.TF_VAR_AWS_ACCOUNT_ID }}" \
          -var="aws_region=${{ vars.TF_VAR_AWS_REGION }}" \
          -var="postgres_db_username=${{ secrets.POSTGRES_DB_USERNAME }}" \
          -var="postgres_db_password=${{ secrets.POSTGRES_DB_PASSWORD }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="route53_zone_id=${{ secrets.ROUTE53_HOSTED_ZONE_ID }}" \
          -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
          -var="ecr_image_tag=${LATEST_TAG}" \
          -var="environment=production" \
          -out=tfplan_full
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Apply (Full)
      id: terraform_apply
      run: terraform apply -auto-approve tfplan_full
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Output Application URL
      id: output_application_url
      run: |
        DOMAIN_NAME=$(terraform output -json domain_name || echo "not_found")
        if [ "$DOMAIN_NAME" == "not_found" ]; then
          echo "Output 'domain_name' not found. Please check your Terraform configuration."
          exit 1
        fi
        echo "Your application is accessible at: https://$DOMAIN_NAME"
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check job status
      id: check_job_status
      run: |
        if [[ ${{ needs.deploy.result }} == 'success' ]]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ steps.check_job_status.outputs.status }}
        text: |
          ${{ steps.check_job_status.outputs.status == 'success' && 'Deployment succeeded! :rocket:' || 'Deployment failed! :x:' }}
          ${{ steps.check_job_status.outputs.status == 'success' && format('Application is accessible at: https://{0}', secrets.DOMAIN_NAME) || '' }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
