name: Deploy Backend

on:
  workflow_run:
    workflows: ["Test and Build Backend"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'backend/terraform/**'
      - '.github/workflows/ci-cd-deploy-backend.yml'

env:
  TF_STATE_BUCKET: ai-wizard-terraform-state-${{ vars.TF_VAR_aws_region }}
  WORKING_DIRECTORY: backend

jobs:
  plan_and_estimate:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'push' && (
        contains(github.event.head_commit.modified, 'backend/terraform/') || 
        contains(github.event.head_commit.modified, '.github/workflows/ci-cd-deploy-backend.yml') ||
        github.ref == 'refs/heads/main'
      ))
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.TF_VAR_aws_region }}
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/AIWizardDeploymentRole
        mask-aws-account-id: 'false'
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ vars.TF_VAR_aws_region }}" \
          -reconfigure
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="aws_account_id=${{ vars.TF_VAR_AWS_ACCOUNT_ID }}" \
          -var="aws_region=${{ vars.TF_VAR_AWS_REGION }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
          -var="route53_zone_id=${{ secrets.ROUTE53_HOSTED_ZONE_ID }}" \
          -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
          -var="environment=production" \
          -out=tfplan
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Setup Infracost
      uses: infracost/actions/setup@v3
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Generate Infracost cost estimate
      run: |
        infracost breakdown --path . \
                            --format json \
                            --out-file infracost-report.json
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Post Infracost comment
      run: |
        infracost comment github --path=infracost-report.json \
                                 --repo=$GITHUB_REPOSITORY \
                                 --github-token=${{ github.token }} \
                                 --behavior=update
        path: ${{ env.WORKING_DIRECTORY }}/terraform/infracost-report.json

    - name: Upload Terraform plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: ${{ env.WORKING_DIRECTORY }}/terraform/tfplan

  approve:
    needs: plan_and_estimate
    runs-on: ubuntu-latest
    steps:
    - name: Manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ github.actor }}
        minimum-approvals: 1
        issue-title: "Approve Terraform changes"
        issue-body: "Please review the Infracost estimate and approve the Terraform changes."
        exclude-workflow-initiator-as-approver: false

  deploy:
    needs: approve
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.TF_VAR_aws_region }}
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/AIWizardDeploymentRole
        mask-aws-account-id: 'false'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Download Terraform plan
      uses: actions/download-artifact@v3
      with:
        name: tfplan
        path: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install
        poetry add zappa
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Deploy with Zappa
      run: |
        poetry run zappa update production
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Terraform Output Application URL
      id: output_application_url
      run: |
        echo "Your application is accessible at: $(terraform output -raw website_url)"
        echo "application_url=$(terraform output -raw website_url)" >> $GITHUB_OUTPUT
      working-directory: ${{ env.WORKING_DIRECTORY }}/terraform

    outputs:
      application_url: ${{ steps.output_application_url.outputs.application_url }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check job status
      id: check_job_status
      run: |
        if [[ ${{ needs.deploy.result }} == 'success' ]]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ steps.check_job_status.outputs.status }}
        text: |
          ${{ steps.check_job_status.outputs.status == 'success' && 'Deployment succeeded! :rocket:' || 'Deployment failed! :x:' }}
          ${{ steps.check_job_status.outputs.status == 'success' && format('Application is accessible at: {0}', needs.deploy.outputs.application_url) || '' }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
